### ISSUE TITLE
Use Offer Templates to present the git clone command correctly

### ISSUE THREAD

**Issue by liamzdenek** [liamzdenek/phabricator-sandstorm#13]
Spin off of #5

**Comment by zarvox** [comment]
Relevant pieces probably live in `DiffusionRepositoryController.php` and `DiffusionCloneURIView.php`.  There may be other places that the "repo uri" shows up in the UI; we'll probably have to adjust all of them similarly, or trim them out where they can't be sanely used directly.

Instead of rendering the URL directly, DiffusionCloneURIView will probably need to grow logic to create an empty iframe and embed some inline script to do the `window.parent.postMessage()` call to request the offer template be made, as well as add a window message event handler to await the reply and set the iframe's location to the offer template URL.

We should figure out how to avoid just dropping the webkey in the URL, lest it be super-easy to leak.  Gitweb's instructions currently use git's credential helper support; we should probably do similarly: https://github.com/dwrensha/gitweb-sandstorm/blob/master/.sandstorm/usr/share/gitweb/sandstorm.js

**Comment by liamzdenek** [comment]
I've done a few naive searches and I'm pretty sure DiffusionRepositoryController is the only place that I need to update.

https://github.com/phacility/phabricator/search?utf8=%E2%9C%93&q=DiffusionCloneURIView
https://github.com/phacility/phabricator/search?utf8=%E2%9C%93&q=getDisplayURI

I can't override getDisplayURI because it looks like some other places rely on it being an actual URI. I don't want to dig too deep and would rather not bother. In addition, I can't configure the display logic at this point. Only the text within the textbox, so I can't load an iframe on the page.

There's also a 'DiffusionURIEditEngine.php' -- not exactly sure what it does/where it is, but it sounds like something that could be troublesome. Note for future.

I've opened [this issue](https://github.com/dwrensha/gitweb-sandstorm/issues/5) on gitweb-sandstorm, as I can't just "borrow" that JS without some legal approval. We'll see.

![](http://i.imgur.com/WOTiIbr.png)
- Some tweaking may be required

**Comment by liamzdenek** [comment]
Resolved in d9c5d388ad7f2b374d6e9ab7707aadcde110d2f1
