### ISSUE TITLE
Consider using X-Sandstorm-Preferred-Handle for `getAccountName()`

### ISSUE THREAD

**Issue by zarvox** [liamzdenek/phabricator-sandstorm#4]
[getAccountID()](https://github.com/liamzdenek/phabricator-sandstorm/blob/master/.sandstorm/src-new/PhutilSandstormAuthAdapter.php#L22) rightly returns a user's long, immutable, unique ID.

[getAccountName()](https://github.com/liamzdenek/phabricator-sandstorm/blob/master/.sandstorm/src-new/PhutilSandstormAuthAdapter.php#L37) seems to also return that same ID, which leads to seeing the huge ID in the UI everywhere.

Perhaps the `X-Sandstorm-Preferred-Handle` header value would be more appropriate for the latter?  It's **not** guaranteed to be unique, but it represents the user's first choice at a short handle, which seems to be the thing that we want to use here.

If Phabricator expects `getAccountName()`'s return value to be unique, we could append integers in the event of a collision.

**Comment by liamzdenek** [comment]
This issue was actually a bit of a PITA vs what I thought it would be.

Phabricator looks at the `phabricator_user.user.userName` column to decide which handle to show all over the site. I was also relying on this for determining which user to log in as.

I resolved it by creating a new table, user_mapper. This maps SS UserIDs to `phabricator_user.user.id,` and updating the login logic to use this table. I had to figure out how to use Phabricator's not-so-well-documented ORM -- LiskDAO. Even though the change is trivial, this was easily several hours of poor docs crawling, and digging through source, and I'm only slightly grumpy.

Whatever. Resolved in 65db108c074ab7352b786fa9dc2bf8978b7f9bd3
